### PR TITLE
Version Added in project file

### PR DESCRIPTION
**Pull request by crvreddy**

### CODE REVIEW

**Comment by adityanarayanp** [comment]
Remove the appSettings from the JSON file also

**Comment by adityanarayanp** [comment]
Remove CA version from the doc

**Comment by adityanarayanp** [comment]
Remove CA version from the doc

**Review by adityanarayanp — APPROVED** [review]

**Review by Vijayalakshmi027 — APPROVED** [review]
Looks fine

**Review by Vijayalakshmi027 — COMMENTED** [review]
fix merge conflict and take latest from devlopment

**Comment by Vijayalakshmi027** [comment]
raised another pr https://github.com/siemens/continuous-clearing/pull/188

**Pull request closed without merging**
